#!/usr/bin/env python3
import argparse
import os
import pathlib
import subprocess
import sys
import yaml

def sh(cmd, check=True):
    return subprocess.run(cmd, shell=True, text=True, check=check, capture_output=True)

def write(path: pathlib.Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--env", required=True)
    ap.add_argument("--spec", required=True)
    args = ap.parse_args()

    env = args.env
    spec_path = pathlib.Path(args.spec)
    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))

    app = (spec.get("components", {}).get("application", {}) or {}).get("name") or spec["metadata"]["name"]
    app = str(app).strip().lower().replace("_", "-").replace(" ", "-")

    ns = (spec.get("components", {}).get("kubernetes", {}) or {}).get("namespace", {}).get("name") or f'{spec["metadata"]["client"]}-{env}'

    image = (((spec.get("components", {}).get("application", {}) or {}).get("container", {}) or {}).get("imageName")) or "REPLACE_ME_IMAGE"
    port = (((spec.get("components", {}).get("application", {}) or {}).get("container", {}) or {}).get("port")) or 8000

    chart_dir = pathlib.Path("k8s/helm") / app
    rt_dir = pathlib.Path(".aiops/runtime") / env / "k8s-bootstrap"

    # Helm chart files
    write(chart_dir / "Chart.yaml", f"""apiVersion: v2
name: {app}
description: Generated by aiops k8s.bootstrap (POC)
type: application
version: 0.1.0
""")

    write(chart_dir / f"values-{env}.yaml", f"""namespace: {ns}

image:
  repository: {image}
  tag: "REPLACE_WITH_SHA"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80
  targetPort: {port}
""")

    write(chart_dir / "templates/namespace.yaml", """apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace }}"
""")

    write(chart_dir / "templates/deployment.yaml", f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app}
  namespace: "{{{{ .Values.namespace }}}}"
spec:
  replicas: {{{{ .Values.replicaCount }}}}
  selector:
    matchLabels:
      app: {app}
  template:
    metadata:
      labels:
        app: {app}
    spec:
      containers:
        - name: {app}
          image: "{{{{ .Values.image.repository }}}}:{{{{ .Values.image.tag }}}}"
          imagePullPolicy: "{{{{ .Values.image.pullPolicy }}}}"
          ports:
            - containerPort: {port}
          env:
            - name: APP_ENV
              value: "{env}"
""")

    write(chart_dir / "templates/service.yaml", f"""apiVersion: v1
kind: Service
metadata:
  name: {app}
  namespace: "{{{{ .Values.namespace }}}}"
spec:
  selector:
    app: {app}
  ports:
    - name: http
      port: "{{{{ .Values.service.port }}}}"
      targetPort: "{{{{ .Values.service.targetPort }}}}"
  type: ClusterIP
""")

    # Runtime artifacts (contract)
    files_written = [
        str(chart_dir / "Chart.yaml"),
        str(chart_dir / f"values-{env}.yaml"),
        str(chart_dir / "templates/namespace.yaml"),
        str(chart_dir / "templates/deployment.yaml"),
        str(chart_dir / "templates/service.yaml"),
    ]
    write(rt_dir / "FILES_WRITTEN.txt", "\n".join(files_written) + "\n")

    # Validation: helm if available
    validation = []
    helm_ok = shutil.which("helm") is not None  # noqa: F821

    rendered_path = rt_dir / "rendered.yaml"
    if helm_ok:
        cmd = f'helm template {app} {chart_dir} -f {chart_dir}/values-{env}.yaml > {rendered_path}'
        try:
            sh(cmd)
            # parse rendered yaml
            list(yaml.safe_load_all(rendered_path.read_text(encoding="utf-8").splitlines(True)))
            validation.append("helm template + rendered YAML parse: OK")
        except Exception as e:
            validation.append(f"helm validation: FAIL ({e})")
    else:
        # fallback: parse templates (works only if scalars are quoted)
        try:
            for p in (chart_dir / "templates").glob("*.yaml"):
                yaml.safe_load(p.read_text(encoding="utf-8"))
            validation.append("template YAML parse (fallback): OK")
        except Exception as e:
            validation.append(f"template YAML parse (fallback): FAIL ({e})")

    write(rt_dir / "SUMMARY.md", f"""# k8s.bootstrap summary ({env})

## Inputs
- ENV: {env}
- SPEC: {spec_path}

## Outputs
- Helm chart: {chart_dir}

## Validation
- {chr(10).join(validation)}

## Notes
- No cluster changes were applied.
""")

    # Enforce “no output.yaml”
    bad = rt_dir / "output.yaml"
    if bad.exists():
        bad.unlink()

    print(f"OK: generated {chart_dir} and {rt_dir}")

if __name__ == "__main__":
    import shutil
    main()